name: crm_dashboard
description: SRMT CRM Dashboard

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  curved_navigation_bar: ^1.0.2
  fl_chart: ^0.35.0
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.5
  build_runner: ^2.3.3
  flutter_riverpod: ^2.0.2
  flutter_native_splash: ^2.2.16
  firebase_core: ^2.16.0
  syncfusion_flutter_gauges: ^22.1.34
  intl: ^0.18.0
  syncfusion_flutter_charts: ^22.1.34
  collection: ^1.14.9
  package_info_plus: ^4.0.2
  syncfusion_flutter_datagrid_export: ^22.1.34-beta
  grouped_list: ^5.1.2
  flutter_bloc: ^8.1.3
  auto_size_text: ^3.0.0
  firebase_database: ^10.2.5
  firebase_storage: ^11.2.5
  cloud_firestore: ^4.8.4
  firebase_auth: ^4.10.0
  pinput: ^3.0.1
  shared_preferences: ^2.2.1
  filter_list: ^1.0.2
  country_picker: ^2.0.21

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: 0.11.0
  flutter_flavor: ^2.0.0
flutter_icons:
  android: true
  ios: true
  image_path_android: "assets/images/app_logo.png"
  image_path_ios: "assets/images/app_logo.png"
  web:
    generate: true
    image_path: "assets/images/app_logo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/app_logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/app_logo.png"
  #Flavors
flavorizr:
  app:
   android:
     flavorDimensions: "flavor-type"
   ios: null0
  flavors:
   dev:
     app:
       name: "SRMT CRM Dev"

     android:
       #bundle identifier
       applicationId: "com.srmt.crm_dashboard.dev"

     ios:
       bundleId: "com.srmt.crm_dashboard.dev"
   qa:
     app:
       name: "SRMT CRM qa"

     android:
      applicationId: "com.srmt.crm_dashboard.qa"

     ios:
      bundleId: "com.srmt.crm_dashboard.qa"
   prod:
     app:
      name: "SRMT CRM"

     android:
      applicationId: "com.srmt.crm_dashboard"

     ios:
      bundleId: "com.srmt.crm_dashboard"


flutter:

  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/
    - assets/svg/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf