const String FIREBASE_AUTH_DATABASE =
    '1GodyKu9ivE3WANRy50p3Jjk5ohUX5leF-J5Zcruiwr4';
const String FIREBASE_LEADS_DATABASE =
    '1uyHZbEZN-WFe69SHiypVSfDMuiVl4wr_gvPwfRbE5Hc';
const String FIREBASE_DEALS_DATABASE =
    '1rozvDwem-IaMMlvt2mO16QS2ZmOqnPqJHEVN-4l0zKc';

const String FIREBASE_AUTH_DB = '${FIREBASE_AUTH_DATABASE}/CRM_Auth';
const String FIREBASE_LEADS_DB = '${FIREBASE_LEADS_DATABASE}/Lead_Details';
const String FIREBASE_DEALS_DB = '${FIREBASE_DEALS_DATABASE}/Deal_Details';
